apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  namespace: homework
  labels:
    app: nginx
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nginx
  namespaceSelector:
    matchNames:
      - homework
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scheme: http