apiVersion: v1
kind: Namespace
metadata:
  name: csi-s3-demo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-data
  namespace: csi-s3-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-s3
